import Layout from "@/components/Layout";
import Head from "next/head";

const Home = () => {
  return (
    <Layout>
      <Head>
        <title>Oh, Ju</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="flex p-3 bg-[gray]">oh Ju</h1>
    </Layout>
  );
};

export default Home;
